<a href="https://colab.research.google.com/github/upasana-crypto/pytorch_training/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

we can use google collab or run locally. Collab uses Linux and nvidia GPUs using cuda. Pytorch version 1.10 atleast required

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


Introduction to tensors: everything in pytorch is a tensor, whether it is a scalar value or something else. Read the doc to understand `torch.tensor`


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.item()
# this is used to convert a tensor into an int

7

In [ ]:
scalar.shape

torch.Size([])

In [ ]:
scalar.ndim
#scalars do not have any dimension

0

In [ ]:
vector= torch.tensor([7,17])
#vectors have 1 dimension : dim = no. of pair of square brackets
vector

tensor([ 7, 17])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

Doubts:

Why is the shape of a scalar 0 whereas of a vector 2 and not 1?

torch.tensor only takes one argument so a final [] is imp, don't forget

In [ ]:
 MATRIX= torch.tensor([[7,8],[9,10]])
 MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
TENSOR = torch.tensor([[[1,2],[2,3]]])

In [ ]:
TENSOR.dtype

torch.int64

In [ ]:
TENSOR[0]

tensor([[1, 2],
        [2, 3]])

In [ ]:
TENSOR[0,1,1]

tensor(3)

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 2, 2])

In [ ]:
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.4760, 0.1288, 0.1198, 0.8123],
         [0.8250, 0.9848, 0.8244, 0.4792],
         [0.7463, 0.2438, 0.8739, 0.4594]],

        [[0.6481, 0.8929, 0.8493, 0.7381],
         [0.4639, 0.7442, 0.7157, 0.2848],
         [0.7082, 0.8931, 0.0271, 0.2239]]])

In [ ]:
random_tensor[1,1,1]

tensor(0.7442)

if not explicitly mentioned, these tensor data type is always float32

In [ ]:
zeroes = torch.zeros(3,4)
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeroes.dtype

torch.float32

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

arange(start,end+1,step)

In [ ]:
one_to_ten = torch.arange(0,11,2)
one_to_ten

tensor([ 0,  2,  4,  6,  8, 10])

In [ ]:
ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0])

These are tensor attributes so properties of a class that the tensor belongs to. if we use size we need torch.size(), which means it is a function

The most common errors faced are with tensor datatypes:
1. Tensors are not of the right datatype, 32 multiplied with 16 etc. ```torch.dtype```
2. Tensors not of the right shape ``torch.shape``
3. Tensors are not on the right device, one is on GPU another on CPU so not possible to have operations with them ``torch.device``

In [ ]:
float_32_tensor = torch.tensor([3,6,9], dtype=None # type of the data eg., float16 or 32 = precision with which a number can be used can be useful for memory
                               ,device=None, requires_grad=False)
float_32_tensor.device

device(type='cpu')

In [ ]:
float_32_tensor.type(torch.float16)

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
rand_tensor = torch.rand(1,2)
rand_tensor

tensor([[0.4904, 0.3436]])

In [ ]:
print(rand_tensor)
print(f"datatype:", rand_tensor.dtype)
print("shape:", rand_tensor.shape)
print("device:", rand_tensor.device)

tensor([[0.4904, 0.3436]])
datatype: torch.float32
shape: torch.Size([1, 2])
device: cpu


In [ ]:
new=torch.tensor([2,3])

In [ ]:
new*10

tensor([20, 30])

In [ ]:
new+10

tensor([12, 13])

In [ ]:
new-1

tensor([1, 2])

In [ ]:
torch.mul(new,10)

tensor([20, 30])

In [ ]:
torch.add(new,10)

tensor([12, 13])

In [ ]:
torch.subtract(new,1)

tensor([1, 2])

Two ways of multiplication in deep learning:
1. element-wise multiplication
2. matrix-multiplication (also called dot-product)

In [ ]:
a = torch.tensor([1,2])
b = torch.tensor([2,3])
ele_mul = a*b
ele_mul

tensor([2, 6])

In [ ]:
torch.mul(a,b)

tensor([2, 6])

In [ ]:
torch.dot(a,b)

tensor(8)

In [ ]:
%%time
torch.matmul(a,b)

CPU times: user 485 µs, sys: 0 ns, total: 485 µs
Wall time: 282 µs


tensor(8)

In [ ]:
# use %%time to see how much time it will take to run a particular cell
%%time
value=0
for i in range(len(a)):
  value+=a[i]*b[i]

print(value)

tensor(8)
CPU times: user 3.66 ms, sys: 0 ns, total: 3.66 ms
Wall time: 3.46 ms


In [1]:
import torch

In [ ]:
# matmul is shortened to mm
tensor_A = torch.tensor([[1,1]])
tensor_B = torch.tensor([[1,1]])
mul= torch.matmul(tensor_A, tensor_B.T)
mul1 = torch.mm(tensor_A, tensor_B.T)
print(mul,mul1)

tensor([[2]]) tensor([[2]])


Tensor Aggregation

In [ ]:
series= torch.arange(0,11,2)
print(f"value of series:\n {series} ")


value of series:
 tensor([ 0,  2,  4,  6,  8, 10]) 


In [ ]:
torch.min(series), series.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(series), series.max()

(tensor(10), tensor(10))

In [ ]:
torch.mean(series.type(torch.float32)), series.type(torch.float32).mean()

(tensor(5.), tensor(5.))

In [ ]:
torch.sum(series), series.sum()

(tensor(30), tensor(30))

Tensor positional aggregate= index value of min and max element will be useful for softmax in deep learning

In [ ]:
series.argmax(), torch.argmax(series)

(tensor(5), tensor(5))

In [ ]:
series.argmin(), torch.argmin(series)

(tensor(0), tensor(0))

Reshaping, view (comes from the same memory)stacking, squeezing (remove all 1 dimensions from a tensor and unsqueezing (adding a 1 dimension to a tensor), permute tensors

In [ ]:
series_reshaped= series.reshape(1,6)
series_reshaped, series_reshaped.shape

(tensor([[ 0,  2,  4,  6,  8, 10]]), torch.Size([1, 6]))

In [ ]:
series_reshaped= series.reshape(6,1)
series_reshaped, series_reshaped.shape

(tensor([[ 0],
         [ 2],
         [ 4],
         [ 6],
         [ 8],
         [10]]), torch.Size([6, 1]))

In [ ]:
series_reshaped= series.reshape(3,2)
series_reshaped, series_reshaped.shape

(tensor([[ 0,  2],
         [ 4,  6],
         [ 8, 10]]), torch.Size([3, 2]))

In [ ]:
z=series.view(1,6)
z

tensor([[ 0,  2,  4,  6,  8, 10]])

z shares the same memory as series so if we change series, z also changes, it is just a view of series



In [ ]:
z[:,5]=1
series

tensor([0, 2, 4, 6, 8, 1])

In [24]:
x= torch.tensor([1,2])
x = x.reshape(1,2)



In [8]:
x_hstack=torch.stack([x,x,x,x], dim=0)
x_hstack, x_hstack.shape

(tensor([[1, 2],
         [1, 2],
         [1, 2],
         [1, 2]]), torch.Size([4, 2]))

In [9]:
x_vstack=torch.stack([x,x,x,x], dim=1)
x_vstack, x_vstack.shape

(tensor([[1, 1, 1, 1],
         [2, 2, 2, 2]]), torch.Size([2, 4]))

In [13]:
torch.hstack([x,x,x,x])

tensor([1, 2, 1, 2, 1, 2, 1, 2])

In [14]:
torch.vstack([x,x,x,x])

tensor([[1, 2],
        [1, 2],
        [1, 2],
        [1, 2]])

In [25]:
x_squeeze = x.squeeze()
x.shape, x_squeeze.shape


(torch.Size([1, 2]), torch.Size([2]))

In [30]:
x_unsqueeze = x.unsqueeze(dim = 2)
x_unsqueeze.shape

torch.Size([1, 2, 1])

In [35]:
 x_permute = x.permute(1,0)
 x_permute.shape

torch.Size([2, 1])

In [38]:
x_permute[1,0] = 5
x

tensor([[1, 5]])

Pytorch tensors and Numpy and how they interact with each other. We start with data in numpy array but later we need it in pytorch tensor

In [39]:
import numpy as np

In [41]:
array = np.arange(1.0, 8.0)
array

array([1., 2., 3., 4., 5., 6., 7.])

In [42]:
tensor = torch.from_numpy(array)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

Reproducibility using random seed


In [43]:
RANDOM_SEED =42
torch.manual_seed(RANDOM_SEED)

a= torch.rand(1,2)
torch.manual_seed(RANDOM_SEED)
b= torch.rand(1,2)
a,b

(tensor([[0.8823, 0.9150]]), tensor([[0.8823, 0.9150]]))

In [1]:
!nvidia-smi

Sun Oct  2 19:43:24 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
import torch
torch.cuda.is_available()

True

Use device agnostic code

In [4]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

we can run one model on one gpu and another on the other, so knowing the number of gpus can be helpful.

In [5]:
torch.cuda.device_count()

1

In [7]:
tensor =torch.rand(1,2)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([[0.7062, 0.3419]], device='cuda:0')

the numpy arrays work only on cpus and not gpus so first we need to convert tensors on gpus to cpus and then convert them to numpy arrays

In [9]:
tensor_on_gpu.cpu().numpy()

array([[0.7062283 , 0.34186774]], dtype=float32)